arch:
  - amd64
os: linux
dist: jammy
git:
  depth: false

language: bash

services:
  - docker

before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.10.2/buildx-v0.10.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  
script:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  - docker buildx create --use
  - docker buildx build --build-arg GH_TOKEN=$GH_TOKEN --push --platform linux/arm64/v8,linux/amd64 --tag moussavdb/application-updater_config_builder:latest .
